myproject/models.py
from myproject import db



##just type the classes for the models###
#########################################


class Puppy(db.Model):

    #establish table name
    __tablename__ = 'puppies'
    #make prymery id
    id = db.Column(db.Integer,primary_key = True)
    #make a name colum  of type text
    name = db.Column(db.Text)
    #One to one relationship
    owner = db.relationship("Owner",backref='puppy',uselist=False)
    
    def __init__(self,name):
        self.name = name

    def __repr__(self):
        if self.owner:
            return f"Puppy name: {self.name} and owner's name: {self.owner.name}"
        else:
            return f"Puppy name: {self.name} and has no owner"
    
class Owner(db.Model):
    __tablename__ = 'owners'
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.Text) 
    puppy_id = db.Column(db.Integer,db.ForeignKey('puppies.id'))

    def __init__(self,name,puppy_id):
        self.name = name
        self.puppy_id = puppy_id

    def __repr__(self):
        return f"Owner name: {self.name}"

myproject/owners/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):
    name = StringField("Name of owner:")
    id = IntegerField("ID of Puppy")
    submit = SubmitField("Add owner")

myproject/puppies/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField



class AddForm(FlaskForm):

    name = StringField('Name of Puppy:')
    submit = SubmitField('Add Puppy')

class DelForm(FlaskForm):

    id = IntegerField('Id Number of Puppy to Remove:')
    submit = SubmitField('Remove Puppy')

myproject/__init__.py
import os 
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate


app = Flask(__name__)

app.config['SECRET_KEY'] = 'mysecretkey'
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///'+ os.path.join(basedir,'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False 


db = SQLAlchemy(app)
Migrate(app,db)

from myproject.puppies.views import puppies_blueprints
from myproject.owners.views import owners_blueprints

app.register_blueprint(owners_blueprints,url_prefix = '/owners')
app.register_blueprint(puppies_blueprints,url_prefix = '/puppies')

myproject/owners/views.py
from flask import Blueprint,render_template,redirect,url_for
from myproject import db
from myproject.models import Owner
from myproject.owners.forms import AddForm 



owners_blueprints = Blueprint('owners' , __name__ , template_folder='templates/owners')

@owners_blueprints.route('/add',methods=['GET','POST'])
def add():

    form = AddForm()

    if form.validate_on_submit():
        name = form.name.data
        pup_id = form.id.data
        #add now owner to database 
        new_owner = Owner(name,pup_id)
        db.session.add(new_owner)
        db.session.commit()
        
        #blueprintname = puppies and #view (function) -> list()
        return redirect(url_for('puppies.list'))
    
    return render_template('add_owner.html' , form=form)


    

myproject/puppies/views.py
from flask import Blueprint,render_template,redirect,url_for
from myproject import db
from myproject.models import Puppy
from myproject.puppies.forms import AddForm,DelForm



puppies_blueprints = Blueprint('puppies' , __name__ , template_folder='templates/puppies')

@puppies_blueprints.route('/add',methods=['GET','POST'])
def add():

    form = AddForm()

    if form.validate_on_submit():
        name = form.name.data
        #add now owner to database 
        new_pup = Puppy(name)
        db.session.add(new_pup)
        db.session.commit()
        
        #blueprintname = puppies and #view (function) -> list()
        return redirect(url_for('puppies.list'))
    
    return render_template('add.html' , form=form)



@puppies_blueprints.route('/list')
def list():
    puppies = Puppy.query.all()
    return render_template('list.html',puppies=puppies)



@puppies_blueprints.route('/delete',methods=['GET','POST'])
def delete():
    form = DelForm()

    if form.validate_on_submit():
        id = form.id.data
        pup = Puppy.query.get(id)

        if pup != None:
            db.session.delete(pup)
            db.session.commit()

        return redirect(url_for('puppies.list'))
    
    return render_template('delete.html',form=form)

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>Adoption</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div class="navbar-nav">
      <a class="nav-item nav-link" href="{{ url_for('index') }}">Home</a>
      <a class="nav-item nav-link" href="{{ url_for('puppies.add') }}">Add Pup</a>
      <a class="nav-item nav-link" href="{{ url_for('puppies.list') }}">List of Pups</a>
      <a class="nav-item nav-link" href="{{ url_for('puppies.delete') }}">Delete Pup</a>
      <a class="nav-item nav-link" href="{{ url_for('owners.add') }}">Add Owner</a>
      

    </div>

</nav>

    {% block content %}

    {% endblock %}
  </body>
</html>

myproject/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Welcome to our Adoption Page</h1>
  <p>Please select one of the links from the nav bar.</p>
</div>
{% endblock %}